
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView resultado;

	private global::Gtk.Table table1;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button3;

	private global::Gtk.Button button4;

	private global::Gtk.Button button5;

	private global::Gtk.Button button6;

	private global::Gtk.Button button7;

	private global::Gtk.Button button8;

	private global::Gtk.Button button9;

	private global::Gtk.Table table2;

	private global::Gtk.Button buttonDividir;

	private global::Gtk.Button buttonMultiplicar;

	private global::Gtk.Button buttonResta;

	private global::Gtk.Button buttonResultado;

	private global::Gtk.Button buttonSuma;

	private global::Gtk.HSeparator hseparator1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		this.GtkScrolledWindow.BorderWidth = ((uint)(3));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.resultado = new global::Gtk.TextView();
		this.resultado.CanFocus = true;
		this.resultado.Name = "resultado";
		this.resultado.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow.Add(this.resultado);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w2.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.BorderWidth = ((uint)(3));
		this.button1.Label = global::Mono.Unix.Catalog.GetString("1");
		this.table1.Add(this.button1);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.button1]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.BorderWidth = ((uint)(3));
		this.button2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.table1.Add(this.button2);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.button2]));
		w4.TopAttach = ((uint)(2));
		w4.BottomAttach = ((uint)(3));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.BorderWidth = ((uint)(3));
		this.button3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.table1.Add(this.button3);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.button3]));
		w5.TopAttach = ((uint)(2));
		w5.BottomAttach = ((uint)(3));
		w5.LeftAttach = ((uint)(2));
		w5.RightAttach = ((uint)(3));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.BorderWidth = ((uint)(3));
		this.button4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.table1.Add(this.button4);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.button4]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.BorderWidth = ((uint)(3));
		this.button5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.table1.Add(this.button5);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.button5]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child table1.Gtk.Table+TableChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.BorderWidth = ((uint)(3));
		this.button6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.table1.Add(this.button6);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.button6]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.LeftAttach = ((uint)(2));
		w8.RightAttach = ((uint)(3));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.BorderWidth = ((uint)(3));
		this.button7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.table1.Add(this.button7);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.button7]));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button8 = new global::Gtk.Button();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.BorderWidth = ((uint)(3));
		this.button8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.table1.Add(this.button8);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.button8]));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.BorderWidth = ((uint)(3));
		this.button9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.table1.Add(this.button9);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.button9]));
		w11.LeftAttach = ((uint)(2));
		w11.RightAttach = ((uint)(3));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add(this.table1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table1]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.buttonDividir = new global::Gtk.Button();
		this.buttonDividir.CanFocus = true;
		this.buttonDividir.Name = "buttonDividir";
		this.buttonDividir.UseUnderline = true;
		this.buttonDividir.BorderWidth = ((uint)(3));
		this.buttonDividir.Label = global::Mono.Unix.Catalog.GetString("/");
		this.table2.Add(this.buttonDividir);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2[this.buttonDividir]));
		w13.TopAttach = ((uint)(1));
		w13.BottomAttach = ((uint)(2));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.buttonMultiplicar = new global::Gtk.Button();
		this.buttonMultiplicar.CanFocus = true;
		this.buttonMultiplicar.Name = "buttonMultiplicar";
		this.buttonMultiplicar.UseUnderline = true;
		this.buttonMultiplicar.BorderWidth = ((uint)(3));
		this.buttonMultiplicar.Label = global::Mono.Unix.Catalog.GetString("*");
		this.table2.Add(this.buttonMultiplicar);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2[this.buttonMultiplicar]));
		w14.TopAttach = ((uint)(1));
		w14.BottomAttach = ((uint)(2));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.buttonResta = new global::Gtk.Button();
		this.buttonResta.CanFocus = true;
		this.buttonResta.Name = "buttonResta";
		this.buttonResta.UseUnderline = true;
		this.buttonResta.BorderWidth = ((uint)(3));
		this.buttonResta.Label = global::Mono.Unix.Catalog.GetString("-");
		this.table2.Add(this.buttonResta);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2[this.buttonResta]));
		w15.TopAttach = ((uint)(2));
		w15.BottomAttach = ((uint)(3));
		w15.LeftAttach = ((uint)(1));
		w15.RightAttach = ((uint)(2));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.buttonResultado = new global::Gtk.Button();
		this.buttonResultado.CanFocus = true;
		this.buttonResultado.Name = "buttonResultado";
		this.buttonResultado.UseUnderline = true;
		this.buttonResultado.BorderWidth = ((uint)(3));
		this.buttonResultado.Label = global::Mono.Unix.Catalog.GetString("=");
		this.table2.Add(this.buttonResultado);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2[this.buttonResultado]));
		w16.TopAttach = ((uint)(1));
		w16.BottomAttach = ((uint)(2));
		w16.LeftAttach = ((uint)(2));
		w16.RightAttach = ((uint)(3));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.buttonSuma = new global::Gtk.Button();
		this.buttonSuma.CanFocus = true;
		this.buttonSuma.Name = "buttonSuma";
		this.buttonSuma.UseUnderline = true;
		this.buttonSuma.BorderWidth = ((uint)(3));
		this.buttonSuma.Label = global::Mono.Unix.Catalog.GetString("+");
		this.table2.Add(this.buttonSuma);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2[this.buttonSuma]));
		w17.TopAttach = ((uint)(2));
		w17.BottomAttach = ((uint)(3));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.table2.Add(this.hseparator1);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2[this.hseparator1]));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(2));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add(this.table2);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table2]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 336;
		this.DefaultHeight = 335;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button9.Pressed += new global::System.EventHandler(this.OnButton9Pressed);
		this.button8.Pressed += new global::System.EventHandler(this.OnButton8Pressed);
		this.button7.Pressed += new global::System.EventHandler(this.OnButton7Pressed);
		this.button5.Pressed += new global::System.EventHandler(this.OnButton5Pressed);
		this.button4.Pressed += new global::System.EventHandler(this.OnButton6Pressed);
		this.button3.Pressed += new global::System.EventHandler(this.OnButton3Pressed);
		this.button2.Pressed += new global::System.EventHandler(this.OnButton2Pressed);
		this.button1.Pressed += new global::System.EventHandler(this.OnButton1Pressed);
		this.buttonSuma.Pressed += new global::System.EventHandler(this.OnButtonSumaPressed);
		this.buttonResultado.Pressed += new global::System.EventHandler(this.OnButtonResultadoPressed);
		this.buttonResta.Pressed += new global::System.EventHandler(this.OnButtonRestaPressed);
		this.buttonMultiplicar.Pressed += new global::System.EventHandler(this.OnButtonMultiplicarPressed);
		this.buttonDividir.Pressed += new global::System.EventHandler(this.OnButtonDividirPressed);
	}
}
